import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { eq, asc } from "drizzle-orm";
import { db } from "@/db";
import { topics, courses } from "@/db/schema";
import { DevTools } from "./dev-tools";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isDev = process.env.NODE_ENV === "development";

  let topicList: { id: string; title: string }[] = [];
  if (isDev) {
    topicList = await db
      .select({ id: topics.id, title: topics.title })
      .from(topics)
      .innerJoin(courses, eq(topics.courseId, courses.id))
      .where(eq(courses.slug, "intro-logic"))
      .orderBy(asc(topics.sortOrder));
  }

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        {isDev && <DevTools topics={topicList} />}
      </body>
    </html>
  );
}
